service: reto-tecnico-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: production
  region: us-east-2

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/People"

  apiGateway:
    shouldStartNameWithService: true

functions:
  getPeople:
    handler: ./src/people.getPeople
    events:
      - http:
          path: people
          method: GET
          cors: true
  getPeopleById:
    handler: ./src/people.getPeopleById
    events:
      - http:
          path: people/{id}
          method: GET
          cors: true
  createPeople:
    handler: ./src/people.createPeople
    events:
      - http:
          path: people
          method: POST
          cors: true

resources: 
    Resources:
      PeopleTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: People
          AttributeDefinitions:
            - AttributeName: persona_id
              AttributeType: S
          KeySchema:
            - AttributeName: persona_id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 10
            WriteCapacityUnits: 10
      